### ISSUE TITLE
Use yaml?

### ISSUE THREAD

**Issue by yields** [segmentio/khaos#92]
not a huge deal, but yaml looks way nicer, plus maintaining a single file instead of a folder of files.

``` yml
package.json: | 
  {
    "name": "{{name}}"
  }

lib/index.js: |
   var debug = require('debug')('{{name}}');
```
